package com.konyaco.keeptally.ui.theme

import androidx.compose.ui.graphics.Color

object KeepTallyColors {
    val md_theme_light_primary = Color(0xFF006b56)
    val md_theme_light_onPrimary = Color(0xFFffffff)
    val md_theme_light_primaryContainer = Color(0xFF7cf8d7)
    val md_theme_light_onPrimaryContainer = Color(0xFF002019)
    val md_theme_light_secondary = Color(0xFF4b635b)
    val md_theme_light_onSecondary = Color(0xFFffffff)
    val md_theme_light_secondaryContainer = Color(0xFFcde9de)
    val md_theme_light_onSecondaryContainer = Color(0xFF072019)
    val md_theme_light_tertiary = Color(0xFF416277)
    val md_theme_light_onTertiary = Color(0xFFffffff)
    val md_theme_light_tertiaryContainer = Color(0xFFc5e7ff)
    val md_theme_light_onTertiaryContainer = Color(0xFF001e2d)
    val md_theme_light_error = Color(0xFFba1b1b)
    val md_theme_light_errorContainer = Color(0xFFffdad4)
    val md_theme_light_onError = Color(0xFFffffff)
    val md_theme_light_onErrorContainer = Color(0xFF410001)
    val md_theme_light_background = Color(0xFFfafdfa)
    val md_theme_light_onBackground = Color(0xFF191c1b)
    val md_theme_light_surface = Color(0xFFfafdfa)
    val md_theme_light_onSurface = Color(0xFF191c1b)
    val md_theme_light_surfaceVariant = Color(0xFFdbe5e0)
    val md_theme_light_onSurfaceVariant = Color(0xFF3f4945)
    val md_theme_light_outline = Color(0xFF707975)
    val md_theme_light_inverseOnSurface = Color(0xFFeff2ef)
    val md_theme_light_inverseSurface = Color(0xFF2d312f)

    val md_theme_dark_primary = Color(0xFF5edbbc)
    val md_theme_dark_onPrimary = Color(0xFF00382c)
    val md_theme_dark_primaryContainer = Color(0xFF005141)
    val md_theme_dark_onPrimaryContainer = Color(0xFF7cf8d7)
    val md_theme_dark_secondary = Color(0xFFb1ccc2)
    val md_theme_dark_onSecondary = Color(0xFF1d352e)
    val md_theme_dark_secondaryContainer = Color(0xFF344b44)
    val md_theme_dark_onSecondaryContainer = Color(0xFFcde9de)
    val md_theme_dark_tertiary = Color(0xFFa9cbe3)
    val md_theme_dark_onTertiary = Color(0xFF0f3447)
    val md_theme_dark_tertiaryContainer = Color(0xFF294a5e)
    val md_theme_dark_onTertiaryContainer = Color(0xFFc5e7ff)
    val md_theme_dark_error = Color(0xFFffb4a9)
    val md_theme_dark_errorContainer = Color(0xFF930006)
    val md_theme_dark_onError = Color(0xFF680003)
    val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
    val md_theme_dark_background = Color(0xFF191c1b)
    val md_theme_dark_onBackground = Color(0xFFe0e3e0)
    val md_theme_dark_surface = Color(0xFF191c1b)
    val md_theme_dark_onSurface = Color(0xFFe0e3e0)
    val md_theme_dark_surfaceVariant = Color(0xFF3f4945)
    val md_theme_dark_onSurfaceVariant = Color(0xFFbfc9c4)
    val md_theme_dark_outline = Color(0xFF89938e)
    val md_theme_dark_inverseOnSurface = Color(0xFF191c1b)
    val md_theme_dark_inverseSurface = Color(0xFFe0e3e0)

    val seed = Color(0xFF00876f)
    val error = Color(0xFFba1b1b)
    val Custom0 = Color(0xFF2196f3)
    val Custom1 = Color(0xFF3f51b5)
    val Custom2 = Color(0xFF6f43c0)
}